#spring:
#  autoconfigure:
#    exclude: 
#    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
#    - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
#    - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
    
    
logging:
  level:
    root: INFO
  
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"